data:
  read:
    - config/locales/devise*.%{locale}.yml
search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"

ignore_unused:
  - activerecord.*
  - date.*
  - simple_form.*
  - time.*
  - titles.*
